name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Generate README
        run: node index.js

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add README.md
          git commit -m "Update README.md [skip ci]"
          git push
